steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-south1-docker.pkg.dev/nodeapp1-0/doc/quickstart-image', './app1' ]
  id: 'Build Docker Image'

  # images:
  # - 'us-south1-docker.pkg.dev/nodeapp1-0/doc/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-south1-docker.pkg.dev/nodeapp1-0/doc/quickstart-image' ]
  id: 'Push Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-south1-docker.pkg.dev/nodeapp1-0/doc/flask-image', './app2' ]
  id: 'Build Docker Image2'

  # images:
  # - 'us-south1-docker.pkg.dev/nodeapp1-0/doc/flask-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-south1-docker.pkg.dev/nodeapp1-0/doc/flask-image' ]
  id: 'Push Docker Image2'


- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=us-south1
    gcloud deploy apply --file deploy/dev.yaml --region=us-south1
    gcloud deploy releases create gke-cicd-pipeline --delivery-pipeline=gke-cicd-pipeline --region=us-south1 --skaffold-file=skaffold.yaml
   


options:
  logging: CLOUD_LOGGING_ONLY
